//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangerSroApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IIS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IIS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MangerSroApp.IIS", typeof(IIS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%
        ///	Response.Write &quot;1&quot;
        ///%&gt;.
        /// </summary>
        internal static string billing_serverstate {
            get {
                return ResourceManager.GetString("billing_serverstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%
        ///Dim objHttp
        ///Dim ServerCheck_SV1
        ///Dim ServerCheck_DB1
        ///
        ///
        ///&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;
        ///On Error Resume Next
        ///Set objHttp = Server.CreateObject(&quot;Msxml2.ServerXMLHTTP&quot;)
        ///
        ///objHttp.open &quot;POST&quot;, &quot;http://www.sro.net/hostcheck.asp&quot;, false
        ///objHttp.setRequestHeader &quot;Content-type&quot;, &quot;application/x-www-form-urlencoded&quot;
        ///objHttp.Send
        ///
        ///If Err.Number &lt;&gt; 0 Then
        ///    If Err.Number &gt;= 400 Then
        ///        ServerCheck_SV1 = -101
        ///    Else
        ///        ServerCheck_SV1 = -102
        ///    End If
        ///Else
        ///	ServerCheck_SV1 = 0
        ///End If
        ///
        ///Set objHttp = No [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string billing_serverstate_bk {
            get {
                return ResourceManager.GetString("billing_serverstate_bk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- #include file = &quot;DBConnect.asp&quot; --&gt;
        ///&lt;!-- #include file = &quot;Function.asp&quot; --&gt;
        ///&lt;!-- #include file = &quot;Class_MD5.asp&quot; --&gt;
        ///
        ///&lt;%
        ///On Error Resume Next
        ///
        ///&apos; Error
        ///If Err.Number &lt;&gt; 0 Then
        ///	Response.Write &quot;-1&quot;
        ///	Response.End
        ///End If
        ///
        ///
        ///
        ///&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos; Req
        ///Dim UserJID
        ///Dim Silk_Offset_Own
        ///Dim Silk_Offset_Gift
        ///Dim Mileage_Offset
        ///Dim ShardID
        ///Dim CharID
        ///Dim ItemID
        ///Dim IP
        ///Dim Valid_Key
        ///
        ///UserJID = Trim(Request(&quot;JID&quot;))
        ///Silk_Offset_Own = Trim(Request(&quot;so&quot;))
        ///Silk_Offset_Gift = Trim(Request(&quot;sg&quot;))
        ///Mileage [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string billing_silkconsume {
            get {
                return ResourceManager.GetString("billing_silkconsume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- #include file = &quot;DBConnect.asp&quot; --&gt;
        ///&lt;!-- #include file = &quot;Function.asp&quot; --&gt;
        ///&lt;!-- #include file = &quot;Class_MD5.asp&quot; --&gt;
        ///
        ///&lt;%
        ///On Error Resume Next
        ///
        ///&apos; Error
        ///If Err.Number &lt;&gt; 0 Then
        ///	Response.Write &quot;-1&quot;
        ///	Response.End
        ///End If
        ///
        ///
        ///
        ///&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos; Req
        ///Dim UserJID
        ///
        ///UserJID = Trim(Request(&quot;JID&quot;))
        ///
        ///UserJID = FilterReqXSS(UserJID)
        ///
        ///
        ///&apos; Error
        ///If UserJID = &quot;&quot; OR IsNull(UserJID) OR IsEmpty(UserJID) Then
        ///	DBConnA.Close
        ///	Set DBConnA = Nothing
        ///
        ///	Response.Write &quot;-2&quot;
        ///	Response.End
        ///End If
        ///
        ///
        ///
        ///&apos;&apos;&apos;&apos;&apos;&apos;&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string billing_silkdatacall {
            get {
                return ResourceManager.GetString("billing_silkdatacall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%
        ///&apos; RSA/MD5 implementation
        ///&apos;
        ///&apos; Version 1.0.1
        ///&apos; Date: 14th April, 2003
        ///&apos; Author: Chris Read
        ///&apos; Home page: http://users.bigpond.net.au/mrjolly/
        ///&apos;
        ///&apos; Most ASP MD5 implementations look relatively the same, the exception with this one is that
        ///&apos; it is a class. Other than that, it&apos;s massaged from the RFC1321 C code and simplified a little.
        ///&apos;
        ///&apos; There are two properties
        ///&apos;	Text - String, text to encode
        ///&apos;	HEXMD5 - String, read-only, MD5 value of Text above
        ///&apos; There are no methods
        ///&apos;
        ///&apos; Private to this clas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Class_MD5 {
            get {
                return ResourceManager.GetString("Class_MD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%
        ///Dim DBConnA, strConnectA
        ///Set DBConnA = Server.CreateObject(&quot;ADODB.Connection&quot;)
        ///strConnectA = &quot;Provider=SQLOLEDB;Data Source=[Host];Initial Catalog=[VsroAccount];user ID=[User];password=[PassWorld];&quot;
        ///DBConnA.Open strConnectA
        ///
        ///%&gt;.
        /// </summary>
        internal static string DBConnect {
            get {
                return ResourceManager.GetString("DBConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%
        ///Function FilterReqXSS(str)
        ///
        ///str = Replace(str, &quot;&lt;&quot;, &quot;&quot;)
        ///str = Replace(str, &quot;&gt;&quot;, &quot;&quot;)
        ///str = Replace(str, &quot;(&quot;, &quot;&quot;)
        ///str = Replace(str, &quot;)&quot;, &quot;&quot;)
        ///str = Replace(str, &quot;{&quot;, &quot;&quot;)
        ///str = Replace(str, &quot;}&quot;, &quot;&quot;)
        ///str = Replace(str, &quot;&apos;&quot;, &quot;&quot;)
        ///str = Replace(str, &quot;%&quot;, &quot;&quot;)
        ///str = Replace(str, &quot;&quot;&quot;&quot;, &quot;&quot;)
        ///str = Replace(str, &quot;!&quot;, &quot;&quot;)
        ///str = Replace(str, &quot;+&quot;, &quot;&quot;)
        ///str = Replace(str, &quot;:&quot;, &quot;&quot;)
        ///str = Replace(str, &quot;;&quot;, &quot;&quot;)
        ///str = Replace(str, &quot;=&quot;, &quot;&quot;)
        ///str = Replace(str, &quot;&amp;&quot;, &quot;&quot;)
        ///
        ///FilterReqXSS = str
        ///
        ///End Function
        ///
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- #include file = &quot;DBConnect.asp&quot; --&gt;
        ///&lt;!-- #include file = &quot;Function.asp&quot; --&gt;
        ///&lt;!-- #include file = &quot;Class_MD5.asp&quot; --&gt;
        ///&lt;%
        ///
        ///On Error Resume Next
        ///
        ///&apos; Error
        ///If Err.Number &lt;&gt; 0 Then
        ///	Response.Write &quot;-1&quot;
        ///	Response.End
        ///End If
        ///
        ///&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos; Check ACL only Call from Billing Server
        ///Dim IP
        ///Dim BillingServer
        ///BillingServer = &quot;88.38.123.110&quot;
        ///IP = Request.ServerVariables(&quot;REMOTE_ADDR&quot;)
        ///&apos;If(IP &lt;&gt; BillingServer) Then
        ///&apos;	Response.Write &quot;ACCESSDENY&quot;
        ///&apos;	Response.End
        ///&apos;End If
        ///&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;
        ///Dim sdSQL
        ///Dim sdRS        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetTotalSilk {
            get {
                return ResourceManager.GetString("GetTotalSilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- #include file = &quot;DBConnect.asp&quot; --&gt;
        ///&lt;!-- #include file = &quot;Function.asp&quot; --&gt;
        ///&lt;!-- #include file = &quot;Class_MD5.asp&quot; --&gt;
        ///&lt;%
        ///
        ///On Error Resume Next
        ///
        ///&apos; Error
        ///If Err.Number &lt;&gt; 0 Then
        ///	Response.Write &quot;ERROR&quot;
        ///	Response.End
        ///End If
        ///
        ///
        ///
        ///&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos; Check ACL only Call from Billing Server
        ///Dim IP
        ///Dim BillingServer
        ///BillingServer = &quot;88.38.123.110&quot;
        ///IP = Request.ServerVariables(&quot;REMOTE_ADDR&quot;)
        ///If(IP &lt;&gt; BillingServer) Then
        ///	Response.Write &quot;ACCESSDENY&quot;
        ///	Response.End
        ///End If
        ///
        ///&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos; Check MD5  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PurchaseSilk {
            get {
                return ResourceManager.GetString("PurchaseSilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- #include file = &quot;DBConnect.asp&quot; --&gt;
        ///&lt;!-- #include file = &quot;Function.asp&quot; --&gt;
        ///&lt;!-- #include file = &quot;Class_MD5.asp&quot; --&gt;
        ///&lt;%
        ///
        ///On Error Resume Next
        ///
        ///&apos; Error
        ///If Err.Number &lt;&gt; 0 Then
        ///	Response.Write &quot;-1&quot;
        ///	Response.End
        ///End If
        ///
        ///
        ///
        ///&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos; Check ACL only Call from Billing Server
        ///Dim IP
        ///Dim BillingServer
        ///BillingServer = &quot;192.168.1.9&quot;
        ///IP = Request.ServerVariables(&quot;REMOTE_ADDR&quot;)
        ///If(IP &lt;&gt; BillingServer) Then
        ///	Response.Write &quot;ACCESSDENY&quot;
        ///	Response.End
        ///End If
        ///
        ///&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos; Check MD5 secre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RefundSilk {
            get {
                return ResourceManager.GetString("RefundSilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ language=&quot;vbscript&quot;%&gt;
        ///&lt;html&gt;&lt;body&gt;The current server time is: 
        ///&lt;%
        ///response.write(Date &amp; &quot; &quot; &amp; Time)
        ///%&gt;
        ///&lt;/body&gt;&lt;/html&gt;
        ///.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
